<a href="https://colab.research.google.com/github/trdquang/Chuong-1_Vao-ra-trong-Python-Vong-lap/blob/main/1_CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Example

In [1]:
import numpy as np

data = np.random.randint(0,5,(5,5))
print(data)

[[2 3 2 1 4]
 [3 0 1 3 2]
 [4 2 4 2 0]
 [3 2 0 4 2]
 [1 1 3 1 2]]


In [2]:
import tensorflow as tf

data_tf = tf.convert_to_tensor(data, dtype=tf.float32)
print(data_tf)

tf.Tensor(
[[2. 3. 2. 1. 4.]
 [3. 0. 1. 3. 2.]
 [4. 2. 4. 2. 0.]
 [3. 2. 0. 4. 2.]
 [1. 1. 3. 1. 2.]], shape=(5, 5), dtype=float32)


In [3]:
data_tf = tf.reshape(data_tf, (1, 5, 5, 1))
print(data_tf.shape)

(1, 5, 5, 1)


In [4]:
import tensorflow.keras as keras

conv_layer = keras.layers.Conv2D(filters=1, kernel_size=(3, 3))

# init
output = conv_layer(data_tf)

In [5]:
weights = conv_layer.get_weights()

In [6]:
print(weights[0].shape)
print(weights[1].shape)

(3, 3, 1, 1)
(1,)


## Number of parameters in a model

In [ ]:
import tensorflow as tf
import tensorflow.keras as keras


model = keras.models.Sequential()
model.add(keras.layers.Conv2D(filters=1, kernel_size=(2, 2), input_shape=(3, 3, 1)))

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 2, 2, 1)           5         
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________


In [ ]:
import tensorflow as tf
import tensorflow.keras as keras


model = keras.models.Sequential()
model.add(keras.layers.Conv2D(filters=1, kernel_size=2, input_shape=(3, 3, 1)))

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 2, 2, 1)           5         
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________


In [ ]:
import tensorflow as tf
import tensorflow.keras as keras


model = keras.models.Sequential()
model.add(keras.layers.Conv2D(1, 2, input_shape=(3, 3, 1)))

model.summary()

In [ ]:
import tensorflow as tf
import tensorflow.keras as keras


model = keras.models.Sequential()
model.add(keras.layers.Conv2D(3, (2, 2), input_shape=(3, 3, 2)))

model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_5 (Conv2D)            (None, 2, 2, 3)           27        
Total params: 27
Trainable params: 27
Non-trainable params: 0
_________________________________________________________________


## Output shape

In [ ]:
import tensorflow as tf
import tensorflow.keras as keras

# create a conv layer
a_conv_layer = keras.layers.Conv2D(filters=1, kernel_size=(2, 2))

# create input data
input_data = tf.random.uniform((1, 3, 3, 1), minval=0, maxval=1)

# call 'a_conv_layer' function
output_data = a_conv_layer(input_data)

print('input_data: \n', input_data.shape)
print('output_data: \n', output_data.shape)

input_data: 
 (1, 3, 3, 1)
output_data: 
 (1, 2, 2, 1)


In [ ]:
import tensorflow as tf
import tensorflow.keras as keras

# create a conv layer
a_conv_layer = keras.layers.Conv2D(filters=32, kernel_size=(2, 2))

# create input data
input_data = tf.random.uniform((1, 3, 3, 2), minval=0, maxval=1)

# call 'a_conv_layer' function
output_data = a_conv_layer(input_data)

print('input_data: \n', input_data.shape)
print('output_data: \n', output_data.shape)

input_data: 
 (1, 3, 3, 2)
output_data: 
 (1, 2, 2, 32)
